spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dingdongserver
    username:
    password:
    driver-class-name: org.h2.Driver
  devtools:
    restart:
      enabled: true
  application:
    name: SpringDingDong

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
